-- CREATE TABLE assets (
--
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     uuid BINARY(16) UNIQUE,
--     ticker VARCHAR(10) NOT NULL, UNIQUE ,
--     purchase_price DECIMAL(18, 2),
--     quantity DECIMAL(18, 2),
--     created_at DATETIME NOT NULL,
--     updated_at DATETIME NOT NULL
--
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;